name: Status Check Functions
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Runs on failure
        if: failure()
        run: echo "This step runs on failure"
      - name: Runs on success
        # This is not needed as it is the default
        if: success()
        run: echo "This step runs on success"
      - name: Always runs
        # if: succeeded() || failed()
        if: always()
        run: echo "This step always runs"
      - name: Runs on cancelled
        if: cancelled()
        run: echo "This step runs on cancelled"
  job-2:
    runs-on: ubuntu-latest
    needs: job-2
    if: failure()
    steps:
      - name: Step 1
        run: echo 'Job 2'

