name: Workflow Dirs & Shells
on: [push]
defaults:
  run:
    shell: bash

jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display Working Directory & List Files
        run: |
          pwd
          ls -al
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: Change Work Directory
        working-directory: /home/runner
        run: pwd
  display-wd-info-windows:
    runs-on: windows-latest
    steps:
      - name: Display Working Directory & List Files
        run: |
          dir
          echo $env:GITHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $envGITHUB_WORKSPACE
      - name: Python Shell
        shell: python
        run: |
          import platform
          print(platform)