name: Workflow Run
on:
  workflow_run:
    workflows: ["Repository events"]
    types: [completed]
jobs:
  echo-string:
    runs-on: ubuntu-latest
    steps:
      - name: Echo string
        run: echo "I was triggered because 'Repository events' workflow was completed"